#!/usr/bin/env ruby

require 'aws-sdk'
require 'net/http'

max_retry = 10
ip_public = '';
while ip_public.length == 0 and max_retry> 0
  max_retry = max_retry - 1
  begin
    metadata_endpoint = 'http://169.254.169.254/latest/meta-data/'
    ip_local = Net::HTTP.get( URI.parse( metadata_endpoint + 'local-ipv4' ) )
    ip_public = Net::HTTP.get( URI.parse( metadata_endpoint + 'public-ipv4' ) )
  
  rescue Exception
     puts "network probably is not initialized yet, sleep a bit"
     sleep 3
  end
end

#puts ip_local
#puts ip_public 


route53 = Aws::Route53::Client.new(
  region: 'us-east-1'
)


record_sets = route53.list_resource_record_sets hosted_zone_id: "ZW4BDITD345AL"

a_records = record_sets[0].select { |r|  r.type == "A" }

a_records.each { |r| 
 r.resource_records[0].value = ip_public
}

changes = a_records.map  { |x| { action:"UPSERT", resource_record_set: x  } }

resp = route53.change_resource_record_sets( {
  hosted_zone_id: "ZW4BDITD345AL",
  change_batch: { changes: changes }
});


puts "dns updated to: " + ip_public
